name: setup-builder
description: Registers a remote builder with Nix
inputs:
  ssh-key:
    description: 'Contents of private SSH key to use with builder'
    required: true
  username:
    description: 'Username to SSH into the builder with'
    required: true
  hostname:
    description: 'Hostname of the builder'
    required: true
  known-host:
    description: 'SSH known host line for the builder'
    required: true
  system:
    description: 'System architecture of the builder'
    required: true
  cores:
    description: 'Number of cores on the builder'
    default: 1
    required: true
  speed-factor:
    description: 'Speed factor of the builder'
    default: 1
    required: true
  features:
    description: 'Features of the builder'
    default: 'big-parallel'
    required: true

runs:
  using: composite
  steps:
    - run: "${{ github.action_path }}/setup-builder.sh"
      shell: bash
      env:
        SSH_KEY: ${{ inputs.ssh-key }}
        USERNAME: ${{ inputs.username }}
        HOSTNAME: ${{ inputs.hostname }}
        KNOWN_HOST: ${{ inputs.known-host }}
        SYSTEM: ${{ inputs.system }}
        CORES: ${{ inputs.cores }}
        SPEED_FACTOR: ${{ inputs.speed-factor }}
        FEATURES: ${{ inputs.features }}
        GITHUB_PATH: ${{ github.path }}
        GITHUB_ENV: ${{ github.env }}
